langstroth/outages/urls.py
from django.urls import re_path
from langstroth.outages import views

app_name = 'outages'
urlpatterns = [
    re_path(r'^$', views.index_page,
            name='list'),
    re_path(r'^(?P<pk>\d+)/$', views.OutageDetailView.as_view(),
            name='detail'),
    re_path(r'^scheduled/$', views.CreateScheduledView.as_view(),
            name='create_scheduled'),
    re_path(r'^unscheduled/$', views.CreateUnscheduledView.as_view(),
            name='create_unscheduled'),
    re_path(r'^(?P<pk>\d+)/add_update/$', views.UpdateOutageView.as_view(),
            name='add_update'),
    re_path(r'^(?P<pk>\d+)/start/$', views.StartOutageView.as_view(),
            name='start'),
    re_path(r'^(?P<pk>\d+)/end/$', views.EndOutageView.as_view(),
            name='end'),
    re_path(r'^(?P<pk>\d+)/cancel/$', views.CancelOutageView.as_view(),
            name='cancel'),
]

langstroth/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import re_path
from django.views.generic.base import RedirectView
from mozilla_django_oidc import views as oidc_views
from rest_framework import routers

from langstroth import error
from langstroth.outages import api
from langstroth import views


router = routers.DefaultRouter()
router.register(r'outages', api.OutageViewSet, basename='outage')


urlpatterns = [

    re_path(r'^$', views.index, name='home'),

    # Composition Visualisations
    re_path(r'^composition/(?P<name>\w+)/$', views.composition,
            name='composition'),
    re_path(r'^composition/(?P<name>\w+)/cores$', views.composition_cores,
            name='composition'),

    # Redirect from old url
    re_path(r'^domain/$',
            RedirectView.as_view(url='/composition/domain', permanent=True),
            name='composition'),

    # Usage Visualisations
    re_path(r'^growth/infrastructure/$', views.growth, name='growth'),
    re_path(r'^growth/users/', include('langstroth.user_statistics.urls')),
    re_path(r'^growth/instance_count$', views.total_instance_count),
    re_path(r'^growth/used_cores$', views.total_used_cores),

    # Allocations Browser
    re_path(r'^allocations/', include('langstroth.nectar_allocations.urls')),

    # Outages
    re_path(r'^outages/', include('langstroth.outages.urls')),

    # API
    re_path(r'^api/v1/', include(router.urls)),

    # Favicon (dev)
    re_path(r'^favicon\.ico$',
            RedirectView.as_view(url='/static/img/favicon.ico')),

    # Timezone detection
    path('tz_detect/', include('tz_detect.urls')),

    # Health checks
    path('healthcheck/', include('health_check.urls')),
]

if settings.USE_OIDC:
    urlpatterns += [
        # Admin Interface
        path('admin/login/',
             oidc_views.OIDCAuthenticationRequestView.as_view(), name='login'),
        path('admin/', admin.site.urls),

        # OIDC auth
        path('oidc/', include('mozilla_django_oidc.urls')),
        path('login/',
             oidc_views.OIDCAuthenticationRequestView.as_view(), name='login'),
    ]
else:
    urlpatterns += [
        # Admin Interface
        path('admin/', admin.site.urls),
        path("login/",
             auth_views.LoginView.as_view(template_name='admin/login.html'),
             name='login'),
    ]

handler500 = error.handler500
handler400 = error.handler400

langstroth/outages/views.py
from django.contrib.auth import mixins
from django.core.exceptions import BadRequest
from django import shortcuts
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView
from django.views.generic.edit import CreateView

from langstroth.outages import filters
from langstroth.outages import forms
from langstroth.outages import models


# Expected state transitions for each Outage status code
STATUS_TRANSITIONS = {
    True: {   # Scheduled outage transitions
        models.STARTED: models.PROGRESSING,
        models.PROGRESSING: models.PROGRESSING,
        models.COMPLETED: models.PROGRESSING   # reopen
    },
    False: {   # Unscheduled outage transitions
        models.INVESTIGATING: models.IDENTIFIED,
        models.IDENTIFIED: models.PROGRESSING,
        models.PROGRESSING: models.FIXED,
        models.FIXED: models.RESOLVED,
        models.RESOLVED: models.PROGRESSING    # reopen
    }
}


def index_page(request):
    f = filters.OutageFilters(
        request.GET,
        is_staff=request.user.is_staff,
        queryset=models.Outage.objects.filter(deleted=False))
    context = {
        "title": "Service Announcements",
        "tagline": "",
        "filter": f
    }
    return shortcuts.render(request, "outages/list.html", context)


class BaseDetailView(DetailView):
    title = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class BaseCreateView(mixins.UserPassesTestMixin,
                     mixins.AccessMixin,
                     CreateView):
    title = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def test_func(self):
        return self.request.user.is_staff


class OutageDetailView(BaseDetailView):
    queryset = models.Outage.objects.filter(deleted=False)
    template_name = "outages/detail.html"
    title = "Announcement Details"


class BaseOutageCreateView(BaseCreateView):
    model = models.Outage

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('outages:detail', args=[self.object.id])


class CreateScheduledView(BaseOutageCreateView):
    """Create a scheduled outage.
    """

    form_class = forms.ScheduledOutageForm
    template_name = "outages/scheduled.html"
    title = "Create Scheduled Announcement"
    initial = {'scheduled': True}


class CreateUnscheduledView(BaseOutageCreateView):
    """Create an unscheduled outage.
    """

    form_class = forms.UnscheduledOutageForm
    template_name = "outages/unscheduled.html"
    title = "Create Unscheduled Announcement"
    initial = {'scheduled': False}


class BaseUpdateCreateView(BaseCreateView):
    model = models.OutageUpdate
    form_class = forms.OutageUpdateForm
    title = "Outage Announcement Update"

    def setup(self, request, *args, **kwargs):
        self.pk = kwargs.pop('pk')
        return super().setup(request, *args, **kwargs)

    def get(self, request, **kwargs):
        self.check_state()
        return super().get(request, **kwargs)

    def post(self, request, **kwargs):
        self.check_state()
        return super().post(request, **kwargs)

    def get_outage(self):
        return models.Outage.objects.exclude(deleted=True).get(pk=self.pk)

    def form_valid(self, form):
        form.instance.outage = self.get_outage()
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def check_state(self):
        pass


class UpdateOutageView(BaseUpdateCreateView):
    """Create an outage update.
    """

    template_name = "outages/add_update.html"

    def get_success_url(self):
        return reverse('outages:detail', args=[self.pk])

    def get_initial(self):
        outage = self.get_outage()
        latest = outage.latest_update
        transitions = STATUS_TRANSITIONS[outage.scheduled]
        return {
            "outage": outage,
            "time": timezone.now(),
            "status": transitions[latest.status],
            "severity": latest.severity
        }

    def check_state(self):
        outage = self.get_outage()
        if not outage.start:
            raise BadRequest(f"Outage {self.pk} in wrong state for update.")


class StartOutageView(BaseUpdateCreateView):
    """Start a scheduled or unsheduled outage.
    """

    template_name = "outages/start.html"

    def get_success_url(self):
        return reverse('outages:detail', args=[self.pk])

    def get_form_class(self):
        outage = self.get_outage()
        if not outage.start:
            # This allows the operator to adjust the start time
            # when starting an outage (for the first time)
            return forms.OutageStartForm
        else:
            return forms.OutageUpdateForm

    def get_initial(self):
        outage = self.get_outage()
        return {
            "outage": outage,
            # For the (first) start of a scheduled outage, we will
            # use the scheduled start time
            "time": (outage.scheduled_start
                     if (outage.scheduled and not outage.start)
                     else timezone.now()),
            "content": ("Scheduled outage started."
                        if outage.scheduled else ""),
            "status": (models.STARTED if outage.scheduled
                       else models.INVESTIGATING),
            "severity": outage.scheduled_severity
        }

    def check_state(self):
        outage = self.get_outage()
        if outage.cancelled or outage.start:
            raise BadRequest(f"Outage {self.pk} in wrong state to start.")


class EndOutageView(BaseUpdateCreateView):
    """End an outage that is in progress.
    """

    template_name = "outages/end.html"
    title = "Outage Announcement Update"

    def get_success_url(self):
        return reverse('outages:detail', args=[self.pk])

    def get_initial(self):
        outage = self.get_outage()
        return {
            "outage": outage,
            "time": timezone.now(),
            "content": ("Scheduled outage completed."
                        if outage.scheduled
                        else "Unscheduled outage resolved."),
            "status": (models.COMPLETED if outage.scheduled
                       else models.RESOLVED),
            "severity": outage.latest_update.severity
        }

    def check_state(self):
        outage = self.get_outage()
        last = outage.latest_update
        if not last or last.status in {models.RESOLVED, models.COMPLETED}:
            raise BadRequest(f"Outage {self.pk} in wrong state to end.")


class CancelOutageView(mixins.UserPassesTestMixin,
                       mixins.AccessMixin,
                       BaseDetailView):
    """Cancel a previously scheduled outage.
    """

    queryset = models.Outage.objects.filter(deleted=False)
    template_name = "outages/cancel.html"
    title = "Confirm Cancellation"

    def get(self, request, **kwargs):
        self._check_state()
        return super().get(request, **kwargs)

    def post(self, request, **kwargs):
        outage = self._check_state()
        outage.cancelled = True
        outage.save()
        return shortcuts.redirect(reverse('outages:list'))

    def _check_state(self):
        outage = self.get_object()
        if outage.cancelled or outage.start or not outage.scheduled:
            raise BadRequest("Outage is in wrong state to cancel.")
        return outage

    def test_func(self):
        return self.request.user.is_staff

langstroth/outages/templates/outages/add_update.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block page-header %}
<div id="page-header" class="container my-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'outages:list' %}">Announcements</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ outage.title }}</li>
    </ol>
  </nav>
  <h1 class="pb-4">Service Announcement</h1>
  <div class="row">
    <div class="col-12 col-md-8 col-xl-9">
      <h5 class="text-uppercase">{{ outage.scheduled_display }} Outage </h5>
      <h3>{{ outage.title }}</h3>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container mb-4">
  <div class="card">
    <div class="card-body">
      <h2>New update</h2>
      <hr />
      <form action="" method="post">
        {% csrf_token %}
        {{ form.outage }}
        <fieldset>
          <div class="mb-3">
            <div class="form-label">Status</div>
            <div>
              {{ form.status }}
              {% for error in form.status.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">Update date & time</div>
            <div>
              {{ form.time }}
              {% for error in form.time.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">Severity</div>
            <div>
              {{ form.severity }}
              {% for error in form.severity.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
            <div id="severity-help" class="form-text">
              Severe - indicates that the problem is highly likely to be disruptive for a significant number of Nectar users.<br />
              Significant - indicates that the problem only affects a small number of users, or that the impact is not significantly disruptive.<br />
              Minimal - indicates that the outage is not likely to be disruptive to anyone.
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">Update message</div>
            <div>
              {{ form.content }}
              {% for error in form.content.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Add Update</button>
        {% if 'outages' in request.META.HTTP_REFERER %}
          <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-link">Back to announcement</a>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_script %}
{{ form.media }}
{% endblock %}

langstroth/outages/templates/outages/cancel.html
{% extends "outages/detail.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="container mb-4">
  <div class="alert alert-danger">
    Are you sure you want to cancel this Service Outage?
  </div>
  <form action="{% url 'outages:cancel' outage.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes</button>
    <button type="button" class="btn btn-secondary"
            onclick="window.location.href='{% url 'outages:detail' outage.id %}';">No</button>
  </form>
</div>
{% endblock %}

langstroth/outages/templates/outages/detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block page-header %}
  <div id="page-header" class="container my-5">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'outages:list' %}">Announcements</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ outage.title }}</li>
      </ol>
    </nav>
    <div class="d-md-flex">
      <h1 class="pb-4">Service Announcement</h1>
      {% if request.user.is_staff %}
        <div class="ms-auto btn-bar">
          {% if outage.end %}
            <a href="{% url 'outages:add_update' outage.id %}" class="btn btn-outline-primary btn-sm" id="reopen"><i class="fas fa-undo"></i> Reopen</a>
          {% elif outage.start %}
            <a href="{% url 'outages:add_update' outage.id %}" class="btn btn-outline-primary btn-sm" id="update"><i class="fa fa-plus"></i> New update</a>
          {% endif %}
          {% if outage.scheduled and not outage.cancelled and not outage.start %}
            <a href="{% url 'outages:start' outage.id %}" class="btn btn-outline-primary btn-sm" id="start"><i class="fa fa-play"></i> Start</a>
            <a href="{% url 'outages:cancel' outage.id %}" class="btn btn-outline-primary btn-sm" id="cancel"><i class="fa fa-times"></i> Cancel</a>
          {% endif %}
          <a href="/admin/outages/outage/{{ outage.id }}/change/" class="btn btn-outline-primary btn-sm" id="edit"><i class="fa fa-pen"></i> Edit</a>
          {% if outage.start and not outage.end %}
            <a href="{% url 'outages:end' outage.id %}" class="btn btn-outline-primary btn-sm" id="end"><i class="fa fa-stop"></i> End</a>
          {% endif %}
        </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-12 col-md-8 col-xl-9" id="outage-{{ outage.id }}">
        <h5 class="text-uppercase">{{ outage.scheduled_display }} Outage </h5>
        <h3>{{ outage.title }}</h3>
        <ul class="list-unstyled">
          {% if request.user.is_staff %}
          <li>
            <strong>Announcement created by:</strong> {{ outage.created_by.username }}
          </li>
          {% endif %}
          {% if outage.scheduled %}
          <li>
             <strong>Scheduled start:</strong> {{ outage.scheduled_start|date:"D, j M Y g:ia (T)" }},
            <strong>Scheduled end:</strong> {{ outage.scheduled_end|date:"D, j M Y g:ia (T)" }}{% if outage.cancelled %},
            <strong>Cancelled</strong>
            {% endif %}
          </li>
          {% endif %}
          {% if outage.start %}
          <li>
            <strong>Outage start:</strong> {{ outage.start|date:"D, j M Y g:ia (T)" }},
            {% if outage.end %}
            <strong>Outage end:</strong> {{ outage.end|date:"D, j M Y g:ia (T)" }}
            {% else %}
            <strong>Outage is ongoing</strong>
            {% endif %}
          </li>
          {% endif %}
          <!-- <li><strong>Affected Zones:</strong></li>
          <li><strong>Affected Services:</strong></li> -->
        </ul>
        {{ outage.description|linebreaks|urlize }}
      </div>
      {% if not outage.cancelled %}
      <div class="col-12 col-md-4 col-xl-3">
        <div class="card bg-light">
          <div class="card-body text-center">
            <h6>Current Status:</h6>
            <p class="h5 text-uppercase">{{ outage.status_display }}</p>
            <h6>Severity:</h6>
            <img class="severity-dial" src="{% get_static_prefix %}img/severity{{ outage.severity }}.svg" />
            <p class="h5 text-uppercase">{{ outage.severity_display }}</p>
            <p>Last modification at: <br />
              <strong>{{ outage.modification_time|date:"D, j M Y g:ia (T)" }}</strong>
            </p>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block content %}
  {% with updates=outage.visible_updates %}
  
  <div class="container mb-4">
    <div class="card">
      <div class="card-body">
        <div class="d-flex">
          <h2>Updates</h2>
        </div>
        <hr />
        {% if updates|length > 0 %}
          <ul class="updates-list">
            {% for update in updates reversed %}
            <li class="update-item {% if forloop.first %}text-dark{% endif %}" id="update-{{ update.id }}">
              <span class="outage-emoji outage-status-{{ update.status }}-emoji"></span>
              <span class="outage-status">{{ update.status_display }}</span>
              <p>
                <strong>{{ update.content|linebreaks|urlize }}</strong><br />
                Update posted
                {% if request.user.is_staff %}
                by {{ update.created_by.username }}
                {% endif %}
                {{ update.time|naturaltime }}.
              </p>
            </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>There are currently no updates.</p>
        {% endif %}
      </div>
    </div>
  </div>
  {% endwith %}
{% endblock %}

langstroth/outages/templates/outages/end.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block page-header %}
<div id="page-header" class="container my-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'outages:list' %}">Announcements</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ outage.title }}</li>
    </ol>
  </nav>
  <h1 class="pb-4">Service Announcement</h1>
  <div class="row">
    <div class="col-12 col-md-8 col-xl-9">
      <h5 class="text-uppercase">{{ outage.scheduled_display }} Outage </h5>
      <h3>{{ outage.title }}</h3>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container mb-4">
  <div class="card">
    <div class="card-body">
      <h2>Final update</h2>
      <hr />
      <form action="" method="post">
        {% csrf_token %}
        {{ form.outage }}
        <fieldset>
          <div class="mb-3">
            <div class="form-label">Status</div>
            <div>
              {{ form.status }}
              {% for error in form.status.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">End date & time</div>
            <div>
              {{ form.time }}
              {% for error in form.time.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">Severity</div>
            <div>
              {{ form.severity }}
              {% for error in form.severity.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">Message</div>
            <div>
              {{ form.content }}
              {% for error in form.content.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        </fieldset>
        <button type="submit" class="btn btn-danger">End the Outage</button>
        {% if 'outages' in request.META.HTTP_REFERER %}
          <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-link">Back to announcement</a>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_script %}
{{ form.media }}
{% endblock %}

langstroth/outages/templates/outages/list.html
{% extends "base.html" %}
{% load static %}

{% block page-header %}
<div id="page-header" class="container my-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Announcements</li>
    </ol>
  </nav>
  <div class="d-md-flex">
    <h1 class="pb-4">Service Announcements</h1>
    {% if request.user.is_staff %}
      <div class="ms-auto btn-bar">
        <a href="{% url 'outages:create_scheduled' %}" id="scheduled" class="btn btn-outline-primary btn-sm">Create scheduled outage</a>
        <a href="{% url 'outages:create_unscheduled' %}" id="unscheduled" class="btn btn-outline-primary btn-sm">Create unscheduled outage</a>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container mb-4">
  <form id="filter-form" method="get">
    <div class="card filter-panel">
      <div class="card-title">Filters</div>
      <div class="card-body">
        <div class="row">
          <div class="col">
            <label for="scheduled_id">Type</label>
            {{ filter.form.scheduled }}
          </div>
          <div class="col">
            <label for="cancelled_id">Cancelled</label>
            {{ filter.form.cancelled }}
          </div>
          <div class="col">
            <label for="activity_id">Activity</label>
            {{ filter.form.activity }}
          </div>
          <div class="col">
            <label for="time_window_id">Time Window</label>
            {{ filter.form.time_window }}
          </div>
          <!-- <div class="col">
            <label for="ordering_id">Ordering</label>
            {{ filter.form.ordering }}
          </div> -->
        </div>
      </div>
    </div>
  </form>
  <p class="text-center text-muted">Showing {{ filter.qs.count }} service announcements.</p>
  {% if filter.qs.count > 0 %}
    <ul class="list-unstyled">
      {% for outage in filter.qs %}
        <div class="card my-4">
          <div class="card-body">
            {% include "outages/outage_summary.html" %}
          </div>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
</div>
{% endblock %}

langstroth/outages/templates/outages/outage_summary.html
{% load static %}
<div class="d-flex">
  <div class="announcement-severity">
    <img class="severity-dial-sm" src="{% get_static_prefix %}img/severity{{ outage.severity }}.svg" />
  </div>
  <div class="announcement-details ps-4">
    <h5 class="text-uppercase">
      {% if outage.status_display == "Resolved" %}(Resolved)&nbsp;{% elif outage.status_display == "Completed" %}(Completed)&nbsp;{% endif %}
      {{ outage.scheduled_display }} Outage
    </h5>
    <h4>
      {{ outage.title }}
    </h4>
    <p>
      <strong>Status:</strong> {{ outage.status_display }}
      {% if outage.start %}
      <strong>Start:</strong> {{ outage.start|date:"D, j M Y g:ia (T)" }}
      {% elif outage.scheduled and outage.scheduled_start %}
      <strong>Start:</strong> {{ outage.scheduled_start|date:"D, j M Y g:ia (T)" }} (scheduled)
      {% endif %}
      {% if outage.end %}
      <strong>End:</strong> {{ outage.end|date:"D, j M Y g:ia (T)" }}
      {% elif outage.scheduled and outage.scheduled_end%}
      <strong>End:</strong> {{ outage.scheduled_end|date:"D, j M Y g:ia (T)" }} (scheduled).
      {% endif %}
    </p>
    <a href="{{ outage.get_absolute_url }}" class="card-link"><span class="card-link-btn">View announcement</span></a>
  </div>
</div>

langstroth/outages/templates/outages/scheduled.html
{% extends "base.html" %}
{% load static %}

{% block page-header %}
<div id="page-header" class="container my-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'outages:list' %}">Announcements</a></li>
      <li class="breadcrumb-item active" aria-current="page">Create Scheduled</li>
    </ol>
  </nav>
  <h1 class="pb-4">Create a Scheduled Outage Announcement</h1>
  <p>Unsure how to create the outage? Instructions are found <a target="_blank" href="https://wiki.rc.nectar.org.au/wiki/Service_Announcements#:~:text=of%20an%20announcement.-,Creating%20and%20managing%20an%20Unscheduled%20Outage,-%5Bedit%5D">in the Nectar Wiki</a>.</p>

</div>
{% endblock %}

{% block content %}
<div class="container mb-4">
  <div class="card">
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        {{ form.scheduled.as_hidden }}
        <fieldset>
          <div class="mb-3">
            <div class="form-label">Title</div>
            <div>
              {{ form.title }}
              {% for error in form.title.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="mb-3">
            <div class="form-label">Description</div>
            <div>
              {{ form.description }}
              {% for error in form.description.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="row mb-3">
            <div class="form-label">Severity</div>
            <div class="col-md-6 col-lg-4">
              {{ form.scheduled_severity }}
              {% for error in form.scheduled_severity.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
            <div id="severity-help" class="form-text">
              Severe - indicates that the problem is highly likely to be disruptive for a significant number of Nectar users.<br />
              Significant - indicates that the problem only affects a small number of users, or that the impact is not significantly disruptive.<br />
              Minimal - indicates that the outage is not likely to be disruptive to anyone.
            </div>
          </div>
          <div class="row mb-3">
            <div class="form-label">Scheduled start date & time</div>
            <div class="col-md-6 col-lg-4">
              {{ form.scheduled_start }}
              {% for error in form.scheduled_start.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="row mb-3">
            <div class="form-label">Schedule end date & time</div>
            <div class="col-md-6 col-lg-4">
              {{ form.scheduled_end }}
              {% for error in form.scheduled_end.errors %}
              <span class="text-danger">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Create</button>
        {% if 'outages' in request.META.HTTP_REFERER %}
          <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-link">Back to announcements</a>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_script %}
{{ form.media }}
{% endblock %}